### ISSUE TITLE
Enterprise Mode not working with LinkClick.aspx

### ISSUE THREAD

**Issue by MaiklT** [DNNCommunity/DNN.Links#12]
Enterprise mode is a feature that opens defined web sites in IE 11, even when a link to that site is clicked in Edge. This is important for sites that contain Java Applets or other Plugins not supported by Edge. See https://technet.microsoft.com/en-us/itpro/microsoft-edge/emie-to-improve-compatibility for more information.
When using DNN's LinkClick.aspx (e.g. to count the clicks or track the users), the site is opening in Edge.

**Comment by valadas** [comment]
I don't know how to reproduce this issue, if still an issue using the latest release, please reopen a new issue with steps to reproduce and an url we can use for testing this behaviour.
