### ISSUE TITLE
Can I get an install package of Links version 4.0.1?

### ISSUE THREAD

**Issue by thosalbert** [DNNCommunity/DNN.Links#13]
I have this working on one of my DNN installations as version 4.0.1. Later versions don't work for me in DNN 9. I wanted to install Links 4.0.1 to my other DNN site,. Itried to create a package from the working one, but it didnt work when I tried to install it. So I'd like to find a version of Links 4.0.1 to install.

Tom

**Comment by EPTamminga** [comment]
I looked into old DNN install packages and found an older version of DNN.Links: Links 4.0.1
[Links_04.00.01_Install.zip](https://github.com/DNNCommunity/DNN.Links/files/1969770/Links_04.00.01_Install.zip)

Does this help?

**Comment by thosalbert** [comment]
Thanks so much Ernst. I actually was able to use the newer version (6.2.3) on our intranet and so far it's working. But I'm glad to have this version and I will test again when I have a chance.

Thanks, I very much appreciate your help.

Tom

**Comment by EPTamminga** [comment]
Hi Tom, 

I am glad I could be of help. If you find any problems in the new version, could you document those here as an issue? That way we could try to find someone to dive in and solve it.

Regards,
Ernst Peter
