### ISSUE TITLE
Control Type can't be changed in existing instances of Links module.

### ISSUE THREAD

**Issue by thosalbert** [DNNCommunity/DNN.Links#16]
Hi, 

I'm using Links version 6.2.3 / DNN 9.1.1 (on a test server ) . 

I have some Links instances which cannot be changed from control type List to Dropdown . 
When I look at the Setting Value in the database, it *does* change from L to D (and back) when I change the setting from the Admin tools in the module. But the display never changes to Dropdown. (I have other instances, which are stuck on Dropdown and can't be changed to List mode). 

This problem applies to instances which I've created in older versions of the Links module. When I create a new instance , I can change its control type.

Anyone else seen this issue? Is there any way to fix it so I  won't have to re-make all my dropdowns if I upgrade to 6.2.3 on our live site?

Thanks

Tom

**Comment by valadas** [comment]
Cannot reproduce using latest version 7.0.0, please try that and reopen an issue if it is still a problem.
