### ISSUE TITLE
Error with install

### ISSUE THREAD

**Issue by moorecreative** [DNNCommunity/DNN.Links#27]
## Describe the bug
Installing into an Evoq Content 8.5 DNN instance where the older DNN Links module has, over time, gone from older versions Links 6.0.2 to newer DNN_Links 6.2.3 the install/upgrade of DNN_Links 7.0.1 failed with an error on install (shown below).

Thing is, since there's a history of older files and upgrades, I'm not sure whether this issue encountered is specific to this instance, or an issue with the upgrade file... I'll try to test on another DNN instance to help test situations

## Software Versions
- DNN Evoq Content: 08.05.00
- Module DNN_Links: 07.00.01

## To Reproduce
Upgrading with DNN_Links installer 7.0.1
Received the following Error in install steps:
---------------------------------------

StartJob | Starting Installation
-- | --
Info | Starting Installation - DNN_Links
Info | Starting Installation - Config
Info | Creating backup of previous version - web.config
Info | Config file updated - web.config
Info | Component installed successfully - Config
Info | Starting Installation - Cleanup
Info | Processing Cleanup File - 7.0.0
Failure | ExceptionSchwabenCode.QuickIO.UnmatchedFileSystemEntryTypeException: FileSystemEntryType not matched! at SchwabenCode.QuickIO.QuickIOFile.InternalFileExists(String uncPath) at DotNetNuke.Common.Utilities.FileSystemUtils.DeleteFiles(Array arrPaths) at DotNetNuke.Services.Installer.Installers.CleanupInstaller.ProcessCleanupFile()
Failure | Installation Failed - Cleanup
Info | Rolling back component install - Config
Info | Config file changes rolled back - web.config
Info | Component rolled back successfully - Config
Info | Installation Failed - DNN_Links
Info | Deleted temporary install folder
EndJob | Installation Failed

---------------------------------------

**Comment by erw13n** [comment]
This is DNN bug when try to run module Cleanup.
Not related to DNN.Links module.

To solve this issue temporary, it require to edit DNN_Links.dnn and remove
`<component type="Cleanup" version="07.00.00" fileName="Cleanup.07.00.00.txt">          
        </component>`

And if possible, remove all files that listed at Cleanup.07.00.00.txt as it no longer use.

**Comment by valadas** [comment]
Is this a Dnn bug where the files do not exist and Dnn tries to delete them anyway.

OR

Are the files there but the worker process account does not have permission to delete them?

**Comment by erw13n** [comment]
This also happen on fresh install at DNN 8 / 8.5
Which probably been fix on DNN 9.0.1 https://github.com/dnnsoftware/Dnn.Platform/pull/1619
as mention at https://dnntracker.atlassian.net/browse/DNN-9202

**Comment by valadas** [comment]
So basically, I guess the problem here is trying to remove the pdb file if it does not exist before Dnn 9.0.1 where that problem got solved right?, so for next release we could remove line one of the 7.0.0 right?

Also, I don't think there is any side effect of just leaving the pdb file if it is there, it is just used when an exception occurs, if not, there is no performance hit by being there right?

**Comment by EPTamminga** [comment]
The cleanup file should not be a problem. 

If the cleanup file is there, the install/upgrade will try to delete the files and/or folder listed in the file. If files or folders do not exist, the process continues without error. 

It might be that deleting a file from the bin folder triggers a restart?

If I see the original error message, I read: "**SchwabenCode.QuickIO**.". Were does that come from?

**Comment by valadas** [comment]
It is a library used by Dnn for file management.

If I understand this correctly, what you say @EPTamminga is what I was also assumming, if a file in the cleanup script does not exist, it ignores it and moves to the next one. 

It looks like there was a bug in Dnn where if the file did not exist, the installed would error out and not continue with the rest of the install. This Dnn issue has been resolved in Dnn 9.0.1, it still produces and error but it continues with the installation since 9.0.1 thanks to https://github.com/dnnsoftware/Dnn.Platform/pull/1619

In addition there will be another improvement where such a situation would product a warning instead of an error, so people don't think incorrectly that the installation failed because there is red text in the installation log, see https://github.com/dnnsoftware/Dnn.Platform/pull/2207

So what I think we should do here is remove the pdb file (which I think is the offending file) from the cleanup script for people upgrading the module and using Dnn before 9.0.1 or thinking (incorectly) there is an error for people upgrading the module on Dnn 9.0.1 up to whataver version will integrate PR 2207.

If I am not mistaken, files to be deleted in the bin folder are scheduled for removal after the restart, or removal does not trigger a restart, not sure how it works exactly, but I have deleted files in the bin folder with cleanup scripts in other modules and it worked...

**Comment by EPTamminga** [comment]
@valadas You are correct. I did not test nor reviewed the issues. Essentially: if a file does not exist, the install (cleanup) process should continue without error. I have used this principle many times.

The bin\ folder delete does not trigger an immediate restart (not sure why, it might be that .NET does not need a restart after a delete, only on adding a file)

**Comment by valadas** [comment]
So basically it is probably only happening on some dnn versions like 9.0.0 or something, not sure what is the equivalent of evoq 8.5...

**Comment by JaySMa** [comment]
Can confirm I'm getting the same error above.  Evoq 9.1.1 installation (upgraded from 8.5.0) and upgrade from Links 6.2.3.

I first tried the 7.0.1 upgrade, received the same error, but showed the module as "No" in uses.  Will try and verify this again.

Rolled back snapshot and tried 7.0.0, received the error and Extensions show that the module as being "in use".  When selecting Folder menu mode, errors out stating that the module isn't available.
Error: Links is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object. at DotNetNuke.Modules.Links.Settings.LoadContentData(String pContentType) at DotNetNuke.Modules.Links.Settings.optLinkModuleType_SelectedIndexChanged(Object sender, EventArgs e) --- End of inner exception stack trace ---

Then tried an upgrade from 7.0.0 to 7.0.1 and received the same installation errors and same error above for folder mode.

**Comment by moorecreative** [comment]
Hi JaySMa, as noted by erw13n earlier in the comments thread, I followed the process to work around the Module Cleanup actions and had success with upgrading the module. 

I manually removed the files which were referenced in the 7.0.1 Module's Cleanup.07.00.00.txt file:

- bin\DotNetNuke.Modules.Links.pdb
- App_Code\Links\Providers\DataProviders\SqlDataProvider\SqlDataProvider.vb
- App_Code\Links\Providers\DataProviders\SqlDataProvider
- App_Code\Links\Providers\DataProviders
- App_Code\Links\Providers
- App_Code\Links\Consts.vb
- App_Code\Links\DataProvider.vb
- App_Code\Links\Enums.vb
- App_Code\Links\LinksController.vb
- App_Code\Links\LinksFriend.vb
- App_Code\Links\LinksInfo.vb
- App_Code\Links\Utils.vb
- App_Code\Links
- DesktopModules\Links\EditLinks.ascx.vb
- DesktopModules\Links\Links.ascx.vb
- DesktopModules\Links\Settings.ascx.vb

and then the extra things needed were for me to update the web.config to remove the line referencing the Links folder from the Code SubDirectories section:

```
      <codeSubDirectories>
        <!--add directoryName="Links" /-->
      </codeSubDirectories>
```

This line had to be commented out/removed, otherwise a .net error was shown regarding the now deleted App_Code\Links folder.

I then created a module version 7.0.1 where the installer had the DNN_Links.dnn updated to comment out the line referencing the Cleanup.07.00.00.txt file:

`        <!--component type="Cleanup" version="07.00.00" fileName="Cleanup.07.00.00.txt"></component-->`

I was then able to complete the Module Install (upgrade) process and see the Links module displaying content correctly on pages.

**Comment by moorecreative** [comment]
@JaySMa ^

**Comment by moorecreative** [comment]
Oh, and @valadas I believe it is that the cleanup is trying to clean up the pdb file, but present, I had only seen the bin/DotNetNuke.Modules.Links.dll file present. So the missing file that it errors on trying to clean out that isn't present is potentially (or at least in this case) the pdb file.

**Comment by valadas** [comment]
Awesome, and there is also a manifest way to edit the web.config, in the config section of the manifest. I would need to re-read the details, but we should be able to update that so there is no manual workarounds to do on upgrades..

**Comment by donker** [comment]
This has been a pet peeve of mine for a while. I hope with PR 2207 on DNN this improves:

https://github.com/dnnsoftware/Dnn.Platform/pull/2207

**Comment by MaiklT** [comment]
I could solve that by changing the lines

    <component type="Cleanup" version="07.00.00" fileName="Cleanup.07.00.00.txt">
    </component>

in the manifest to

    <component type="Cleanup" version="07.00.00">
       <files>
          <file>
             <path>bin</path>
             <name>DotNetNuke.Modules.Links.pdb</name>
          </file>
          <file>
             <path>App_Code\Links\Providers\DataProviders\SqlDataProvider</path>
             <name>SqlDataProvider.vb</name>
          </file>
          <file>
             <path>App_Code\Links\Providers\DataProviders\SqlDataProvider\</path>
          </file>
          <file>
             <path>App_Code\Links\Providers\DataProviders\</path>
          </file>
          <file>
             <path>App_Code\Links\Providers\</path>
          </file>
          <file>
             <path>App_Code\Links</path>
             <name>Consts.vb</name>
          </file>
          <file>
             <path>App_Code\Links</path>
             <name>DataProvider.vb</name>
          </file>
          <file>
             <path>App_Code\Links</path>
             <name>Enums.vb</name>
          </file>
          <file>
             <path>App_Code\Links</path>
             <name>LinksController.vb</name>
          </file>
          <file>
             <path>App_Code\Links</path>
             <name>LinksFriend.vb</name>
          </file>
          <file>
             <path>App_Code\Links</path>
             <name>LinksInfo.vb</name>
          </file>
          <file>
             <path>App_Code\Links</path>
             <name>Utils.vb</name>
          </file>
          <file>
             <path>App_Code\Links\</path>
          </file>
          <file>
             <path>DesktopModules\Links</path>
             <name>EditLinks.ascx.vb</name>
          </file>
          <file>
             <path>DesktopModules\Links</path>
             <name>Links.ascx.vb</name>
          </file>
          <file>
             <path>DesktopModules\Links</path>
             <name>Settings.ascx.vb</name>
          </file>
       </files>
    </component>

and deleted the file **Cleanup.07.00.00.txt**. Worked for Upgrade in DNN 8.0.4.

**Comment by valadas** [comment]
closing this as it was a Dnn bug, it should no longer happen on recent versions
