### ISSUE TITLE
Module Crashes On Page

### ISSUE THREAD

**Issue by TekkGuy** [DNNCommunity/DNN.Links#29]
## Describe the bug
After installing the module, any page that uses it is blank in view mode and shows an error in edit mode.

## Software Versions
- DNN: 09.02.01
- Module: 07.00.01

## Error log
Message: Could not find stored procedure 'dnnLinks_GetLinks'.
StackTrace:
InnerMessage:Could not find stored procedure 'dnnLinks_GetLinks'.
InnerStackTrace: at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData() at System.Data.SqlClient.SqlDataReader.get_MetaData() at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted) at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest) at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry) at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method) at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method) at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior) at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior) at Glimpse.Ado.AlternateType.GlimpseDbCommand.ExecuteDbDataReader(CommandBehavior behavior) at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader() at PetaPoco.Database.d__2`1.MoveNext() at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source) at PetaPoco.Database.Fetch[T](String sql, Object[] args) at DotNetNuke.Data.PetaPoco.PetaPocoDataContext.ExecuteQuery[T](CommandType type, String sql, Object[] args) at DotNetNuke.Modules.Links.Components.LinkController.GetLinks(Int32 moduleId) in D:\websites\dnn920\DesktopModules\DNN.Links\Components\LinkController.cs:line 238 at DotNetNuke.Modules.Links.Links.Page_Load(Object sender, EventArgs e) in D:\websites\dnn920\DesktopModules\DNN.Links\Links.ascx.cs:line 542

**Comment by w3devpro** [comment]
Can confirm the issue (Critical and blocking all access). Cause seems to be the use of an objectqualifier (OQ) on db objects: if used (e.g. fws_dnnLinks_GetLinks) module will not work. Temp workaround: remove OQ from sproc names. New install & fix much appreciated.

**Comment by valadas** [comment]
There has been a couple of issues with the same problem, it was handled on another issue and will be resolved in the next release shortly
