### ISSUE TITLE
Not Azure Compatible

### ISSUE THREAD

**Issue by cpaterra** [DNNCommunity/DNN.Links#3]
Try to install this module in Windows Azure environment (EE 7.3.3.117), but a pop-up displays with the warning: This package is not verified to be compatible with Azure SQL Database.

If you ignore the warning and continue the installation, it will fail.

**Comment by valadas** [comment]
Should be fixed with the latest release, I do not have Azure to actually try it but the Extension Verification Service says it should be fine now. Please reopen a new issue if not.
