### ISSUE TITLE
Import doesn't work

### ISSUE THREAD

**Issue by meffj00** [DNNCommunity/DNN.Links#30]
In a link module I wanted to export the links to import them into another link module. Unfortunately, the links were not imported.

**Comment by meffj00** [comment]
No one with that has this problem too?

**Comment by valadas** [comment]
Where they both of the same version, If soo, please add the version number at least so this can be tested. Thanks.

**Comment by NiharikaRaut** [comment]
Even I am facing issue importing Links module on Evoq Content version 9.3.0.
When I export a particular module, it gets exported successfully  into an xml file.
When I am trying to import the same module I exported earlier, it shows nothing. Please help out.

**Comment by valadas** [comment]
Is this Evoq specific, was this tried on Dnn.Platform 9.4.4 ?

**Comment by NiharikaRaut** [comment]
I tried it on DNN 9.4.1 as well as DNN 9.4.4. I am getting same issue. It imports nothing into the new module. So I don't think the issue is specific to Evoq platform.

**Comment by valadas** [comment]
Ok, thanks
