### ISSUE TITLE
Appearance of "GO" link using 4.0.1 version - odd behavior. 

### ISSUE THREAD

**Issue by thosalbert** [DNNCommunity/DNN.Links#31]
Hi - I've been keeping on using Links 4.0.1 on our site, since it was working directly from selecting items in the select box, *without* the "Go" link. I'm running DNN 9.1.1. (I've worked with Links 6.2.3 on a test server and worked around the "Go" link, but on production site, was keeping version 4.0.1

On our test server, I was trying a trial of DNN Sharp My Tokens. When I would install MyTokens, it would break Links 4.0.1 (showed error in admin mode, and didn't show the Links module on the page). When I reinstall (repair) Links 4.0.1, it works, but now, it includes the "Go" link. I never saw the "Go" link in version 4.0.1 before (only in 6.2.3). Any idea what's going on?

I tried this a couple times on test server, with the same behavior. And it stays the same, even when I uninstall the MyTokens Extension.

None of this is a real problem, I can work around it - but just curious and wanted to let you know about it. 

Thanks

Tom

**Comment by valadas** [comment]
Closing as it duplicates #7
