### ISSUE TITLE
Links Module breaking in Evoq Content version 9.3.0

### ISSUE THREAD

**Issue by NiharikaRaut** [DNNCommunity/DNN.Links#32]
I installed links 6.2.3 on Evoq Content 9.1.1 and it was working perfectly fine. But we had to upgrade Evoq content from 9.1.1 to 9.3.0. In 9.3.0, the links module 6.2.3 is completely breaking. So I upgraded links module to 7.0.1 version and can see some of the links module partially breaking. When I click the pencil icon next to links instead of opening the section where we enter title, provide url etc, it is showing erro 'object reference not set to an instance of an object'.

- Evoq Content: 9.3.0
- Module: Links module 6.2.3 and 7.0.1

**Comment by thogan44** [comment]
I am having the same issue

**Comment by jncraig** [comment]
Update the Links module to the current version:  https://github.com/DNNCommunity/DNN.Links/releases

The transition from 9.1.1 to 9.2 and above came with well advertised breaking changes and have been repaired in the later versions of most DNN modules.

**Comment by thogan44** [comment]
![linksVersion](https://user-images.githubusercontent.com/17881041/57396264-0ab34800-7198-11e9-85e6-08f18fa97ecb.PNG)

its already that version

**Comment by thogan44** [comment]
Small observation, if the link is a new link then I am able to add, update and delete. It is the old ones that I am having issues with.

**Comment by thogan44** [comment]
Workaround... I was able to update the last two columns [RefreshInterval] and [GrantRoles] to a default value and I was able to edit all the old entries. I was not overly concerned about the [RefreshInterval] and [GrantRoles] these pages rarely get changed and view permissions are handled by the page mostly sometimes the module but never by the individual content. However it is cool that you can set that.

**Comment by NiharikaRaut** [comment]
Thanks for the reply.
The workaround suggested by you worked for me.
