### ISSUE TITLE
Links not visible when logged out

### ISSUE THREAD

**Issue by meffj00** [DNNCommunity/DNN.Links#33]
## Describe the bug
After the conversion of DNN EVOQ to DNN Platform 9.2.2. We are experiencing problems with the updated DNN Link module version 7.01. If you enter a new link in a converted link module, it will only visible when be logged in and when logged out.

## Software Versions
- DNN: 09..02.02
- Link Module: 07.00.01

## To Reproduce
With a converted link module.
Add a new link in the converted link module an don't choose any roles. 
When logged in the link is visible. When logged out, the link is not visible.
The module setting 'Use Permissions' is 'Yes'. 
If you want the change it to 'No' you cannot save the setting. 
A look in the table ModuleSettings setting 'use permissions' says 'false'.
The setting will not change, even if I do the reverse nothing happens!
In the settings from the table Link i see the value GrantRoles ;0; for the not visible link and ;-2; for the visible link.
 
New link module
If you place a new module on a page, the module will work as expected!
The module setting 'Use Permissions' is 'No' (not using any roles, just everyone). 

## Workaround
When you add a new link in a converted Link module you have to change GrantRoles settings for the link in ;-2; otherwise the new link will not shown when logged out! 

## Expected behavior
After the conversion from EVOQ to DNN Platform you expect when you add a new link this is shown., even if you are logged out!

## Strange logic?
The logic I don't understand? In the Link module you can set 'No' use permissions (if you could save the setting). When you enter a new link, you can still ticked a role per link?
The possibility to choose a role should not be shown in my opinion!

**Comment by meffj00** [comment]
Any reaction?

**Comment by valadas** [comment]
I am not sure to understand the issue and the meaning of a converted link's module. Can you indicate clear steps to make it happen in platform ?

**Comment by valadas** [comment]
Closing this due to lack of response
