### ISSUE TITLE
PopupTrigger code within class name

### ISSUE THREAD

**Issue by moorecreative** [DNNCommunity/DNN.Links#34]
## PopupTrigger code(?) Appears within generated link code
Is this proper functioning of the generated menu code?

When the setting is set to MENU, the generated LI list of menu items includes a class of "Normal<%PopupTrigger%>"

as in example:
```
<a href="http://domainname.com/ParentPage/Page-Name-Here" id="dnn_ctr459_Links_lstLinks_linkHyp_1" class="Normal<%#PopupTrigger%>" alt="alt text here." target="_self">
                    Page Name Here
                </a>
```

## Software Versions
- DNN: 09.02.02
- Module: 07.00.01

## To Reproduce
1. Go to the Links module instance Module Settings
2. Within the Link Settings tab, set the module mode to MENU and select a parent page
4. view the generated source code of the menu list to see the  class="Normal<%#PopupTrigger%>"
content

## Expected behavior
Unsure... this could be intended behavior that I am unaware of, but wanted to report for review.

**Comment by valadas** [comment]
We are removing support for the telerik popup and this will be removed at the same time. Closing this issue for now as we already have one for the telerik removal.
