### ISSUE TITLE
Symbols following links

### ISSUE THREAD

**Issue by NiharikaRaut** [DNNCommunity/DNN.Links#35]
Is it possible to have an icon after a link?
For example : I have placed a links module onto a page. Now I am adding a link and I have attached pdf to that link, so I want the small pdf icon to appear after the link. similarly, if I add next link and attach an excel to that link, an excel icon should appear after the link.

**Comment by valadas** [comment]
As it is now, an icon can be added but shows up before the link and it needs to be set link by link. Pull requests are welcome though if someone wants to implement this.
