### ISSUE TITLE
Links dropdown instances break when upgrading to version 7.0.1

### ISSUE THREAD

**Issue by thosalbert** [DNNCommunity/DNN.Links#39]
I have many instances of Links that I created years ago using Links version 4. 
I'm upgrading DNN to 9.2.2 and then 9.3.2, and need to upgrade Links in order to do so. When I upgrade Links to 7.0.1, it breaks the Links lists . For each Links instance, I get two errors on the page which look like:

**Error:** Quick Find is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object. at DotNetNuke.Modules.Links.Links.Page_Load(Object sender, EventArgs e) --- End of inner exception stack trace ---
------------------------------------------------

In Admin logs, I get:
--------------------------------------------------
**ModuleId:**510
**ModuleDefId:**119
**FriendlyName:**Links
**ModuleControlSource:**DesktopModules/Links/Links.ascx
**AbsoluteURL:**/Default.aspx
**DefaultDataProvider:**DotNetNuke.Data.SqlDataProvider, DotNetNuke
**ExceptionGUID:**7e201717-f57a-4873-b9b3-42fc4f47c2de
**AssemblyVersion:**9.1.1
**PortalId:**0
**UserId:**389
**TabId:**40
**RawUrl:**/Home.aspx
**Referrer:**http://sccinternettest/Home.aspx
**UserAgent:**Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
**ExceptionHash:**gLYPsBPv57CkbMoI7QRubZb1sGk=
**Message:**Object reference not set to an instance of an object.
**StackTrace:**
**InnerMessage:**Object reference not set to an instance of an object.
**InnerStackTrace:**
at DotNetNuke.Modules.Links.Links.Page_Load(Object sender, EventArgs e)
**Source:**
**FileName:**
**FileLineNumber:**0
**FileColumnNumber:**0
**Method:**
**Server Name:** SCTAS35
----------------------------------------

I am able to create new instances of Links dropdowns, but it would be great if I could get the existing ones to work (and didn't have to re-build them all) . I can tell that the data is still there. Any suggestions for fixing the error?

Thanks

Tom

**Comment by valadas** [comment]
You could try to download the debug symbols package and drop those files in the site bin folder, this will get a bit more details into the error log. Another thing is log files in /Portals/Default/logs folder that may have a bit more details. My guess would be some thing relating to a data difference like empty strings vs nulls or some such, you you are confortable using sql you could compare the data between an existing one and a new one to maybe spot what is different. I have seen in other modules a setting data difference too and sometimes just resaving the settings fixes it...

**Comment by thosalbert** [comment]
Thanks Valadas - 
I'm not familiar with debug symbols package but I will look into it. 
I looked at the Default/logs folder and the messages are about the same (copied below) 

I'll take a look at the SQL database - So far, I have tried playing around in Admin mode and changing settings and changing them back again, etc without any success. Let me know if you have any other ideas, I appreciate it!

Tom

Error log: 
2019-10-07 18:00:29,331 [SCTAS35][Thread:44][ERROR] DotNetNuke.Services.Exceptions.Exceptions - FriendlyMessage="Error: Quick Find is currently unavailable." ctrl="ASP.desktopmodules_links_links_ascx" exc="System.NullReferenceException: Object reference not set to an instance of an object.

**Comment by thabaum** [comment]
Have you made sure all cache is cleared and restarted DNN, the refreshed the pages?
SETTINGS > SERVER clear cache and restart application.

**Comment by thosalbert** [comment]
Thanks for both of your suggestions - 

Per Valades suggestion, I checked out the database and found the problem. and I was able to easily fix it with a query to update one of the fields (GrantRoles) from a NULL to a string.

So - I think I'm good!!

Thanks

**Comment by valadas** [comment]
Great to know it was fixed, a lot of those older modules where converted from VB to C# and well it is a bit more strict with values and these are kinda hard to test without the accompanying data :) So keep this issue to fix this properly for next versions. Thanks for reporting back.

**Comment by SCullman** [comment]
Can this be related to https://github.com/dnnsoftware/Dnn.Platform/issues/2969?

**Comment by Xand0r** [comment]
I'm seeing this same issue. I have a ton of old Link modules, and am running DNN 9.4.4. When I update the Links module from 3.3.7 to 7.0.1, my Links modules currently configured to display as Dropdowns break with the same error.

Poking around the DB, here are the TabModuleSettings records that match the Links module that is set as a dropdown that's not loading:

`SELECT TOP 1000 [TabModuleID]
      ,[SettingName]
      ,[SettingValue]
      ,[CreatedByUserID]
      ,[CreatedOnDate]
      ,[LastModifiedByUserID]
      ,[LastModifiedOnDate]
  FROM [REMOVED].[dbo].[TabModuleSettings] where TabModuleID = 10658

TabModuleID	SettingName	SettingValue	CreatedByUserID	CreatedOnDate	LastModifiedByUserID	LastModifiedOnDate
1343	AllowIndex	True	539	2020-02-20 13:13:37.573	539	2020-02-20 13:13:37.573
1343	displayinfo	N	NULL	NULL	429	2014-07-30 09:32:51.697
1343	hideadminborder	False	429	2014-07-30 09:32:51.553	429	2014-07-30 09:32:51.553
1343	icon		NULL	NULL	429	2014-07-30 09:32:51.700
1343	linkcontrol	D	NULL	NULL	429	2014-07-30 09:32:51.693
1343	linkview	V	NULL	NULL	429	2014-07-30 09:32:51.697
1343	nowrap	W	NULL	NULL	429	2014-07-30 09:32:51.700
1343	searchonce	False	429	2014-07-30 09:32:51.587	429	2014-07-30 09:32:51.587`

By comparison, when I make a new Links module and go into its settings and select Dropdown and save that change, it doesn't seem to store that information in the same spot, as this is all I get for that TabModuleSettings record:

`SELECT TOP 1000 [TabModuleID]
      ,[TabID]
      ,[ModuleID]
      ,[PaneName]
      ,[ModuleOrder]
      ,[CacheTime]
      ,[Alignment]
      ,[Color]
      ,[Border]
      ,[IconFile]
      ,[Visibility]
      ,[ContainerSrc]
      ,[DisplayTitle]
      ,[DisplayPrint]
      ,[DisplaySyndicate]
      ,[IsWebSlice]
      ,[WebSliceTitle]
      ,[WebSliceExpiryDate]
      ,[WebSliceTTL]
      ,[CreatedByUserID]
      ,[CreatedOnDate]
      ,[LastModifiedByUserID]
      ,[LastModifiedOnDate]
      ,[IsDeleted]
      ,[CacheMethod]
      ,[ModuleTitle]
      ,[Header]
      ,[Footer]
      ,[CultureCode]
      ,[UniqueId]
      ,[VersionGuid]
      ,[DefaultLanguageGuid]
      ,[LocalizedVersionGuid]
  FROM [REMOVED].[dbo].[TabModules] where TabModuleID = 10658

TabModuleID	TabID	ModuleID	PaneName	ModuleOrder	CacheTime	Alignment	Color	Border	IconFile	Visibility	ContainerSrc	DisplayTitle	DisplayPrint	DisplaySyndicate	IsWebSlice	WebSliceTitle	WebSliceExpiryDate	WebSliceTTL	CreatedByUserID	CreatedOnDate	LastModifiedByUserID	LastModifiedOnDate	IsDeleted	CacheMethod	ModuleTitle	Header	Footer	CultureCode	UniqueId	VersionGuid	DefaultLanguageGuid	LocalizedVersionGuid
10658	58	8041	RightRightPane	5	0	NULL	NULL	NULL	NULL	0	NULL	1	0	0	0		NULL	0	539	2020-02-20 13:17:52.420	539	2020-02-20 13:19:36.300	0	FileModuleCachingProvider	Links	NULL	NULL		E711C1C1-FEEA-4B51-8E85-D087BC5466E2	7E78C099-3265-4CB4-90A0-F4511999C2E6	NULL	BBEB364A-AD1F-4FE6-B17F-26D6B0038657`

If in the first table I change the linkcontrol value from 'D' to 'L', the module will load, and will not have errors.

However, when I go to change the module settings to from List to Dropdown and save the change, nothing happens, the window closes as if it saved, but the Links are dtill a list, and if I go back into the settings, List is still selected.

Similarlly, I am unable to change any existing Link modules displaying as a list to now display as a Dropdown.

This error might be related to that.

`02/20/2020 13:16:29
General Exception
 
 
AbsoluteURL DefaultDataProvider DotNetNuke.Data.SqlDataProvider DotNetNuke 
AbsoluteURL:

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:6b96ba88-5978-4d5d-95e1-035e5b58b1db

AssemblyVersion:

PortalId:-1

UserId:-1

TabId:-1

RawUrl:

Referrer:

UserAgent:

ExceptionHash:fg5Od6sLKqh2BUER46wIGvijRRA=

Message:Method not found: 'System.Collections.Hashtable DotNetNuke.Entities.Portals.PortalSettings.GetModuleSettings(Int32)'.

StackTrace:

   at DotNetNuke.Modules.Announcements.AnnouncementsController.GetSearchItems(ModuleInfo ModInfo)
   at DotNetNuke.Services.Search.ModuleIndexer.GetSearchIndexItems(Int32 portalId)
InnerMessage:

InnerStackTrace:

Source:DotNetNuke.Modules.Announcements

FileName:

FileLineNumber:0

FileColumnNumber:0

Method:

Server Name: REMOVED`

Maybe this information will help troubleshoot the issue, as you said old data is hard to test for.

**Comment by valadas** [comment]
As we don't have much to go on other than the workaround, I am closing this issue unless we know what needs to be done.
