### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by JaySMa** [DNNCommunity/DNN.Links#40]
Installing v7.0.1 within Evoq 8.5.0.  Running .NET 4.8.0.

During the installation process, error reports:

Failure | ExceptionSchwabenCode.QuickIO.UnmatchedFileSystemEntryTypeException: FileSystemEntryType not matched!    at SchwabenCode.QuickIO.QuickIOFile.InternalFileExists(String uncPath)    at DotNetNuke.Common.Utilities.FileSystemUtils.DeleteFiles(Array arrPaths)    at DotNetNuke.Services.Installer.Installers.CleanupInstaller.ProcessCleanupFile()
-- | --
Failure | Installation Failed - Cleanup

**Comment by valadas** [comment]
This is caused by a Dnn bug with the cleanup tasks on files that do not exists for some reason or another, the good advice would be to upgrade Dnn. If for some reason that is not possible, then you could edit the Cleanup.07.00.00.txt text file to remove it's content which I believe would work.
