### ISSUE TITLE
Menu mode listing trashed Tabs and other issues

### ISSUE THREAD

**Issue by giovaboy** [DNNCommunity/DNN.Links#45]
## Describe the bug
If setted to "Menu", the links module will display also trashed tabs, disabled tabs and not visible tabs.

## Software Versions
- DNN: v. 09.02.02 (178)
- Module: 7.0.1

## To Reproduce
1. Add a Links module 
2. Apply the Menu mode in Module Settings
3. Point the module to any page with some sub pages. Save
4. Move any of the sub pages to trash bin.
5. Look at your Links module, the link to the trashed page still there

## Expected behavior
Trashed pages should not by listed 

## Additional context
The same behaviour happens with disabled pages and not visible pages

**Comment by giovaboy** [comment]
I've fixed it with this code in the Switch-Case for the Menu Type in "Links.ascx.cs", but I'm not ready to commit a pull request: 
```
List<TabInfo> allTabs = TabController.GetTabsByParent(moduleContentItemInt, this.PortalId);
foreach (DotNetNuke.Entities.Tabs.TabInfo t in allTabs) {
  if (!t.IsDeleted && t.IsVisible && !t.DisableLink)
    {
      tabsToShow.Add(t);
     } 
```

**Comment by valadas** [comment]
Can I ask why you are not ready for a pull request ?
