### ISSUE TITLE
Unique ID attribute in the <LI> for each list item.

### ISSUE THREAD

**Issue by dgingold** [DNNCommunity/DNN.Links#48]
WCAG 2.0 analyzer wants a unique ID attribute for each item in the list.
each list item begins <li id="itemLi" class="linkItem"...
perhaps could be <li id="itemLi_1" class... ??

## Software Versions
- DNN: 9.x
- Module: 7.00.01

## To Reproduce
1. add several link items to a links module
2. inspect element on any list item. They're each id="itemLi"

## Expected behavior
when generating the view, for each item output id="itemLI_"+itemnumber?

**Comment by noahbast** [comment]
I just came here to add a bug report for this.  We're focusing more and more on accessibility and the tools do not like duplicate element IDs.

**Comment by noahbast** [comment]
I tried changing the list item element like this and it appears to be working.  This was only a cursory test and we are only using the most basic features of the module, so more testing is needed.
            <li id="itemLi" ClientIDMode="Predictable" class="linkitem <%# Horizontal %>" <%# NoWrap %>>
