### ISSUE TITLE
Remove Telerik Dependencies

### ISSUE THREAD

**Issue by MaiklT** [DNNCommunity/DNN.Links#52]
## Describe the bug
The [Telerik Dependency Report](https://github.com/IowaComputerGurus/DnnTelerikIdentifier) reports a dependency to DotNetNuke.Modules.Links.dll

## Software Versions
- DNN: 09.08.00
- Module: 07.00.01

## Expected behavior
Telerik Dependencies should be removed for security reasons.

**Comment by valadas** [comment]
I took a quick look at this (wanted to make this part of 7.1.0), there was a bit more dependencies than I though, I was expecting a couple of dropdowns in settings and the tooltip but found out the whole Friends template is all Telerik. So this will take some effort.

**Comment by valadas** [comment]
I would like to know if any people using this module uses the Friends mode ?
