### ISSUE TITLE
"This Module is configured to show dynamic Data. Please use Modulesettings to change"

### ISSUE THREAD

**Issue by jdsemma** [DNNCommunity/DNN.Links#6]
Where, exactly, can you change this text, if at all? The only place I can find is in EditLinks.ascx, which is suboptimal. There's no place in the module settings that I can find that allows you to change (or add) any sort of text to the module.

Our use case is that we'd like to replace that line of text with some instructions ("PDFs only", that sort of thing).

**Comment by EPTamminga** [comment]
If this is the only place that has this text, then it is an omission. All text should be configurable in the language .resx files and editable by the language editor in host or admin.

**Comment by jdsemma** [comment]
I see localization values for "Force Content Refresh?" through "View order must be a number or an empty string" -- the above string is NOT showing in EditLinks.ascx.Host.resx

**Comment by EPTamminga** [comment]
Any text should be in the file "EditLinks.ascx.resx" in the install pack. If that is not the case, then it is a bug/issue.

**Comment by jdsemma** [comment]
Any update? This is a bug/issue.

**Comment by EPTamminga** [comment]
Please submit a pull request with the fix.

**Comment by jdsemma** [comment]
Sorry, but that's hardly a helpful answer for me. I'm not enough of a programmer to be able to do the fix. If I were, I'd have already done it.

**Comment by valadas** [comment]
I can confirm this is hardcoded and not localized. Will fix soon.
