### ISSUE TITLE
After update to DNN 9.9.1, "Link type: File" shows "You don't have permission to see the files on this site"

### ISSUE THREAD

**Issue by thosalbert** [DNNCommunity/DNN.Links#62]
## Describe the bug
After updating to DNN 9.9.1, when the user selects "Add Link" and then selects "Link type: **File (A File on Your Site)**" a message appears: "You don't have permission to see the files on this site", and user is unable to browse/select a File to link. 

## Software Versions
- DNN: 9.9.1 (bug did not occur before upgrading DNN - worked correctly in DNN 9.6.1)
- Module: Links 8.0.0 (also occurred in 7.0.1 (only with DNN 9.9.1))

## To Reproduce
1. Log in as admin to DNN page
2. In a Links module, select "Add Link"
3. Select "File" in the "Link Type:" section
4. A message "You don't have permission to see the files on this site."

## Expected behavior
"File Location" and "File Name" Dropdowns should open to allow selecting a file from the webserver

## Error log
No error log

**Comment by valadas** [comment]
It is working fine for me here, there must be some sort of permission issues not related to the links module
