### ISSUE TITLE
After update to 9.10.2 Files components are missing while in Edit or Add Link

### ISSUE THREAD

**Issue by mbuelsing** [DNNCommunity/DNN.Links#64]
## Describe the bug
After upgrading to DNN 9.10.2, while trying to add or edit a link, when you change the "Link Type" option it to "File" it causes a blink, but "File Location", "File Name" and "Upload File" do not appear. Upgrading Links module from 7.0.1 to 8.0.0 did not change this behavior.

## Software Versions
- DNN: 9.10.2
- Module: 8.0.0

## To Reproduce
1. Click "Add Link"
2. Change "Link Type" to "File"
3. There is a blink.
4. "File Location", "File Name" and "Upload File" do not appear.

## Expected behavior
Expected "File Location", "File Name" and "Upload File" to appear so a link to a file could be created or altered.

## Screenshots

![Links](https://user-images.githubusercontent.com/53478975/189990591-d20756e3-4251-4f01-9b4a-b991ea564ad2.png)

## Error log
There are no errors in the Admin Log

## Additional context
-Existing links to files are still clickable and open their target files.
-Tried with a Bootstrap 4 theme and a Bootstrap 5 theme. The behavior was identical.

**Comment by mbuelsing** [comment]
This site was DNN 8.0.4 before it was upgraded to DNN 9.1.1 --> 9.3.2 --> 9.10.2, one after the other.

**Comment by WillStrohl** [comment]
You mentioned that there are no errors in the Admin Log, but do you see anything that appears to be related in the Log4NET log files?  

`/Portals/_default/Logs/`

**Comment by mbuelsing** [comment]
To answer the question, I opened an existing link, chose a page link type, then changed to "File" Link Type, which malfunctioned, and then checked the  2022.09.13.log.resources file. What I found at that timestamp is posted below. Is Orizonti related to the Links module?

I do not have an Orizonti Nuke News module installed in this instance, however it may have been installed and removed years ago. This site has been around for years.

2022-09-13 15:50:35,611 [CS01025945][Thread:1][ERROR] DotNetNuke.Web.Extensions.StartupExtensions - Unable to configure services for Orizonti_NukeNews.SqlDataProvider, Version=1.0.2104.22688, Culture=neutral, PublicKeyToken=null, see exception for details 
- LoaderException: Could not load file or assembly 'Orizonti_NukeNews, Version=1.0.2104.22688, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at DotNetNuke.DependencyInjection.Extensions.TypeExtensions.SafeGetTypes(Assembly assembly, ILog logger)
2022-09-13 15:50:36,127 [CS01025945][Thread:1][ERROR] DotNetNuke.Web.Mvc.Extensions.StartupExtensions - Unable to configure services for Orizonti_NukeNews.SqlDataProvider, Version=1.0.2104.22688, Culture=neutral, PublicKeyToken=null, see exception for details 
- LoaderException: Could not load file or assembly 'Orizonti_NukeNews, Version=1.0.2104.22688, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at DotNetNuke.DependencyInjection.Extensions.TypeExtensions.SafeGetTypes(Assembly assembly, ILog logger)
2022-09-13 15:50:37,143 [CS01025945][Thread:1][ERROR] DotNetNuke.Web.DependencyInjectionInitialize - Unable to configure services for Orizonti_NukeNews.SqlDataProvider, Version=1.0.2104.22688, Culture=neutral, PublicKeyToken=null, see exception for details 
- LoaderException: Could not load file or assembly 'Orizonti_NukeNews, Version=1.0.2104.22688, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at DotNetNuke.DependencyInjection.Extensions.TypeExtensions.SafeGetTypes(Assembly assembly, ILog logger)

**Comment by mbuelsing** [comment]
Also worth noting, I looked in the module settings, then "Links Settings" tab. In the "Display Icon" section, a blue message says, "You don't have permission to see the files on this site." I didn't expect that. I'm logged in as host and the File Manager allows me full access to the folders and files.
- that message is similar to the issue reported just before mine, https://github.com/DNNCommunity/DNN.Links/issues/62 [https://github.com/DNNCommunity/DNN.Links/issues/62](url)
-Related to that, I noticed a folder that is marked as "Secure" and there are many folders and files in there. That is where most of the images and pdfs in this site are stored. That folder is not marked as Secure in the site before the upgrades. I still have that site operational.

**Comment by WillStrohl** [comment]
> Is Orizonti related to the Links module?

No. This should be completely unrelated.  

> Also worth noting, I looked in the module settings, then "Links Settings" tab. In the "Display Icon" section, a blue message says, "You don't have permission to see the files on this site." I didn't expect that. I'm logged in as host and the File Manager allows me full access to the folders and files.

Have you rechecked the permissions the website is running under at the hosting level?  If you need to reapply the permissions, I'd suggest recycling the application pool as well before you recheck the issue.

**Comment by mbuelsing** [comment]
Will, yes I have done that twice now with no change. I'm still troubleshooting myself and open to suggestions. I have seen a couple similar posts but they dropped off without posting their resolutions.

**Comment by WillStrohl** [comment]
By the way, I just formally verified that `Orizonti` isn't a dependency for this module.  I pulled the latest code and performed a search on the entire source and there are no hits on that.  

Permissions definitely sound like the right place to look.  Too bad that's not the fix.  

What kind of hosting environment is this?  Is it possible an antivirus program might be getting in the way?

**Comment by mbuelsing** [comment]
Apparent Progress: Following a lead from similar reported issue, I acquired the SQL Stored Procedure named "GetFoldersByPermissions" from the non-upgraded version of this site from DNN 8.0.4 and pasted it into the upgraded version of the site (DNN 9.10.2) and after clearing the cache, the Links module correctly shows the controls for linking to files like it should and the Image tool in the HTML module now correctly shows all the folders from which to get an image. Both situations are back to normal operation. 

Returning to the stored procedures, I compared them and see one line has been changed in the DNN 9.10.2 version - or another previous version between 8.0.4 and 9.10.2- I can't be sure which one.  Here are before and after lines.


SP: GetFoldersByPermissions

DNN 8.0.4

Line 68:
AND FP.FolderID NOT IN (SELECT DISTINCT folderid FROM dbo.[FolderPermission] WHERE allowaccess=0 AND (userid=@UserId OR roleid=-1 OR roleid IN (SELECT roleid FROM dbo.[UserRoles] WHERE UserID=@UserId)))	

DNN 9.10.2

Line 68:
AND FP.PermissionID NOT IN (SELECT DISTINCT PermissionID FROM dbo.[FolderPermission] WHERE allowaccess=0 AND (userid=@UserId OR roleid=-1 OR roleid IN (SELECT roleid FROM dbo.[UserRoles] WHERE UserID=@UserId)))		

Difference:
FP.FolderID has been swapped out and FP.PermissionID has been swapped in

At this point I request that the difference be analyzed by someone more in-touch with the permissions particulars than I am.

**Comment by erw13n** [comment]
It probably related to https://github.com/dnnsoftware/Dnn.Platform/issues/3004

**Comment by WillStrohl** [comment]
> At this point I request that the difference be analyzed by someone more in-touch with the permissions particulars than I am.

I think maybe @sleupold would be a good person to confirm that.  Definitely a better person to confirm this than I am.  :)

**Comment by mbuelsing** [comment]
Thank you for your help Will !!!

**Comment by valadas** [comment]
I cannot reproduce this issue, I am assuming it was some DNN bug reading the comments here. If I am wrong and there is a way to reproduce it with the Links module latest code, please comment and I'll reopen this issue...
