### ISSUE TITLE
Cannot link a file

### ISSUE THREAD

**Issue by meffj00** [DNNCommunity/DNN.Links#65]
On DNN 9.11 we are using module Links 8.0.0 and we authorised a user. The user cannot link a file and get an error 'You are not authorized to upload files!' We got the same error in the module Documents! Something wrong with the URL-controller?

**Comment by WillStrohl** [comment]
Does that user also have the appropriate permissions for the folder(s) that the module is set to upload to?

**Comment by erw13n** [comment]
I think this issue is related to https://github.com/dnnsoftware/Dnn.Platform/issues/5423

**Comment by skamphuis** [comment]
I submitted a PR with a fix on the URLControl that addresses this. If that gets accepted, that should fix this issue too.

**Comment by valadas** [comment]
Since there was no more activity on this and the other PR got merged, I am assuming this was resolved. If I am wrong, please comment and I'll be glad to re-open
