### ISSUE TITLE
Friendly Name error - can't send header after header's been sent

### ISSUE THREAD

**Issue by dgingold** [DNNCommunity/DNN.Links#66]
I have thousands of these errors, and i clear the logs regularly because they build up quickly on a very busy site. The module's used multiple times on 92 pages of the site. We use the links module in folder mode to display pdf documents. The problem's been happening since v9.10.2 and continues in v9.11. Links module is 8.0.0. the error is:
01/22/2023 15:01:15  Module Load Exception 
Will County Illinois 
ModuleId 1817 ModuleDefId 140 FriendlyName SHNH Soft Goods Bid ModuleContr 
ModuleId:1817

ModuleDefId:140

FriendlyName:SHNH Soft Goods Bid

ModuleControlSource:DesktopModules/Links/Links.ascx

AbsoluteURL:/Default.aspx

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:7e0e9984-bde1-4310-9f86-8026722f71ef

AssemblyVersion:9.11.0

PortalId:0

UserId:-1

TabId:481

RawUrl:/County-Offices/Administration/Purchasing/2011Awarded-Bids/FileId/2353

Referrer:https://www.google.com/

UserAgent:Mozilla/5.0 (Linux; Android 12; SM-S908U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Mobile Safari/537.36

ExceptionHash:XdTznXRMOTdaPF6R59pDGe6tyOc=

Message:Server cannot clear headers after HTTP headers have been sent.

StackTrace:

InnerMessage:Server cannot clear headers after HTTP headers have been sent.

InnerStackTrace:

   at System.Web.HttpResponse.ClearHeaders()
   at DotNetNuke.Services.FileSystem.FileManager.WriteFileToHttpContext(IFileInfo file, ContentDisposition contentDisposition)
   at DotNetNuke.Services.FileSystem.FileManager.WriteFileToResponse(IFileInfo file, ContentDisposition contentDisposition)
   at DotNetNuke.Modules.Links.Links.Page_Load(Object sender, EventArgs e)
Source:

FileName:

FileLineNumber:0

FileColumnNumber:0

Method:

Server Name: CS01025920

Referrer sometimes is a search page, sometimes is on the site itself.

**Comment by valadas** [comment]
Fixed in #67
